### PR TITLE
Desktop version styling - Home page

### PR DESCRIPTION
**Pull request by teckim**
### In this pull request:

- Added Styling for desktop version.
- Fixed Stylelint issues.

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi @teckim , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description


# Required Changes ♻️

- [ ] Great work only a slight change, in this project highlighted below, your button doesn't have a hover effect and also when pressed kindly fix it.

image
 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by teckim** [comment]
Hi @danmainah, thank you for your review.

I believe that the hover and focus effects are working fine.

**Comment by danmainah** [comment]
Hello @teckim  check out this video for more explanation [click here](https://www.loom.com/share/a465a4e50455421ab020661d6d9f6320)

**Comment by teckim** [comment]
Hi @danmainah, thank you for your comment.

For that button, I did it in purpose just to demonstrate the `disabled` state.

**Review by KDlamini — APPROVED** [review]
### Hi @teckim 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ Great PR title
✔️ Good PR description
✔️ Very responsive website
✔️ No linters errors

# Status: Approved ✔️ 

oscars-standing-ovation
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
